name = "flare-drive"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
compatibility_date = "2024-12-11"

[env.production]
name = "flare-drive-production"
route = "flare-drive.example.com/*"
zone_id = "your-zone-id"

[site]
bucket = "./build"
entry-point = "workers-site"

[build]
command = "npm run build"
cwd = "./"
